### ISSUE TITLE
cannot upgrade on Ventura 13.6.1 (22G313)

### ISSUE THREAD

**Issue by cbertelli** [fredowski/homebrew-pspp#7]
This is the output of brew upgrade:

==> Installing fredowski/pspp/pspp
==> ./configure --without-perl-module --disable-silent-rules
==> make
Last 15 lines from /Users/carlo/Library/Logs/Homebrew/pspp/02.make:
make[2]: *** [src/ui/gui/psppire-builder-wrapper.o] Error 1
1 error generated.
make[2]: *** [src/ui/gui/psppire-executor.o] Error 1
1 error generated.
1 error generated.
make[2]: *** [src/ui/gui/psppire-goto-case-dialog.o] Error 1
make[2]: *** [src/ui/gui/psppire-find-dialog.o] Error 1
1 error generated.
make[2]: *** [src/ui/gui/psppire-helper.o] Error 1
1 error generated.
make[2]: *** [src/ui/gui/psppire-help-menu.o] Error 1
1 error generated.
make[2]: *** [src/ui/gui/psppire-main.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Sorry for reporting it without further investigation, just to make you aware of the emerging issue. If more information can be useful, I can provide it.

**Comment by fredowski** [comment]
Thanks for your report. I cannot reproduce this on MacOS 12.7.4. The MacOS CI runners also work on 12.7. So some more information would be useful. Could you install with "brew install pspp --verbose" ?

**Comment by cbertelli** [comment]
The log of 
brew upgrade pspp --verbose
is in the following gist:
https://gist.github.com/cbertelli/4ad919f4f093952e9a2da6ccf4ea6b8e

**Comment by cbertelli** [comment]
Here is the gist:
https://gist.github.com/cbertelli/4ad919f4f093952e9a2da6ccf4ea6b8e

**Comment by fredowski** [comment]
Dear Carlo, thanks for your compile run! The problem is related to g_memdup2 where two definitions clash. 

```
gl/uniwidth/libgl_la-width.o >/dev/null 2>&1
In file included from src/ui/gui/builder-wrapper.c:21:
In file included from src/ui/gui/builder-wrapper.h:21:
In file included from src/ui/gui/include/gtk/gtk.h:26:
In file included from /usr/local/Cellar/gtk+3/3.24.41/include/gtk-3.0/gtk/gtk.h:30:
In file included from /usr/local/Cellar/gtk+3/3.24.41/include/gtk-3.0/gdk/gdk.h:30:
In file included from /usr/local/Cellar/gtk+3/3.24.41/include/gtk-3.0/gdk/gdkconfig.h:8:
src/ui/gui/include/glib.h:36:1: error: static declaration of 'g_memdup2' follows non-static declaration
g_memdup2 (gconstpointer mem,
^
/usr/local/Cellar/glib/2.80.0_2/include/glib-2.0/glib/gstrfuncs.h:354:23: note: previous declaration is here
gpointer              g_memdup2        (gconstpointer mem,
                      ^
In file included from src/ui/gui/entry-dialog.c:19:
In file included from ./src/ui/gui/entry-dialog.h:20:
In file included from src/ui/gui/include/gtk/gtk.h:26:
In file included from /usr/local/Cellar/gtk+3/3.24.41/include/gtk-3.0/gtk/gtk.h:30:
In file included from /usr/local/Cellar/gtk+3/3.24.41/include/gtk-3.0/gdk/gdk.h:30:
In file included from /usr/local/Cellar/gtk+3/3.24.41/include/gtk-3.0/gdk/gdkconfig.h:8:
src/ui/gui/include/glib.h:36:1: error: static declaration of 'g_memdup2' follows non-static declaration
g_memdup2 (gconstpointer mem,
^
/usr/local/Cellar/glib/2.80.0_2/include/glib-2.0/glib/gstrfuncs.h:354:23: note: previous declaration is here
gpointer              g_memdup2        (gconstpointer mem,
                      ^
clang -DHAVE_CONFIG_H -DEXEEXT=\"\" -I.  -I"./gl" -I"./gl" -DINSTALLDIR=\"/usr/local/Cellar/pspp/2.0.1/bin\" -I"./src" -I"./lib" -Isrc -I"./src/language/commands" -I"/private/tmp/pspp-20240330-55729-geyzop/pspp-2.0.1/src/language/expressions" -I"./src/language/expressions" -Isrc -Isrc/ui/gui/include -I/usr/local/Cellar/glib/2.80.0_2/include -I/usr/local/Cellar/glib/2.80.0_2/include/glib-2.0 -
```

We introduced some compatiblity code some time ago 

https://savannah.gnu.org/bugs/index.php?62747

but there seems to be some problem with that now. So we need to look into this.

**Comment by cbertelli** [comment]
Thank you very much for explanation and for pushing the bug backwards
to the source, as it seems to be something not related to MacOS.
Grazie.
c

**Comment by fredowski** [comment]
I switched the github ci runner from macos-latest to macos-13. The build does not fail:

https://github.com/fredowski/homebrew-pspp/actions/runs/8506494318

The MacOS version on that github build server is 13.6.5. So maybe there is something wrong in your brew environment such that the build fails. You can see that on the build server the test for g_memdup2 succeeds:

2024-04-01T09:40:29.9845040Z checking for g_memdup2 in -lglib-2.0... yes

while in your run this test fails.

**Comment by cbertelli** [comment]
Thank you. I'll check it out.
c

**Comment by fredowski** [comment]
Any news on this?

**Comment by cbertelli** [comment]
Sorry for not replying. It didn't, after trying for some time, I gave up.
If it useful for anyone, I'll follow the procedure you suggested once
again, asking you new directives I cannot advance.
c
